# Generated by Django 4.0.3 on 2022-03-25 18:47

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=72)),
                ('middle_name', models.CharField(blank=True, max_length=72, null=True)),
                ('last_name', models.CharField(max_length=72)),
                ('properties', sortedm2m.fields.SortedManyToManyField(help_text=None, to='properties.property')),
            ],
        ),
    ]
